AllCops:
  Exclude:
    - 'gemfiles/vendor/**/*'
Metrics/LineLength:
  Max: 120
Style/MultilineBlockChain:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'spec/benchmarks/*.rb'
