AllCops:
  Exclude:
    - 'lib/rails-session_cookie.rb'
    - 'gemfiles/vendor/**/*'
Metrics/LineLength:
  Max: 120
Style/MultilineBlockChain:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Lint/AmbiguousBlockAssociation:
  Enabled: false
